"""triagelab - a synthetic static-triage toolkit.

SAFETY: this project never handles real malicious code. Every sample under
fixtures/ is generated by fixtures/generate_samples.py and is inert data.
"""

__version__ = "0.1.0"
