"""Generate synthetic triage samples.

Every file this writes is inert: plain text and pseudo-random bytes. The
"suspicious" content is nothing but API *names* written as ASCII strings so the
pattern matcher has something to find. There is no executable payload here and
this project must never contain a real malicious sample.
"""

from __future__ import annotations

import random
from pathlib import Path

OUT = Path(__file__).parent / "samples"
SEED = 20260906

BENIGN_TEXT = """README for the widget service
This build script compiles the widget parser and runs the unit tests.
Configuration lives in config.yaml. Logging is handled by the standard library.
Contact the maintainers before changing the serialization format.
"""

SAMPLES: dict[str, dict] = {
    "benign_readme.bin": {"text": BENIGN_TEXT * 3, "random_bytes": 0},
    "config_dump.bin": {
        "text": "hostname=lab-01\nGetComputerName\nipconfig /all\nlog_level=debug\n" * 4,
        "random_bytes": 0,
    },
    "downloader_stub.bin": {
        "text": "URLDownloadToFile\nInternetOpenUrl\ncmd.exe /c\nstage2.dat\n" * 3,
        "random_bytes": 256,
    },
    "packed_blob.bin": {"text": "UPX0\nUPX1\n", "random_bytes": 8192},
    "injector_stub.bin": {
        "text": (
            "VirtualAllocEx\nWriteProcessMemory\nCreateRemoteThread\n"
            "IsDebuggerPresent\nRegSetValueEx\nSOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run\n"
        )
        * 2,
        "random_bytes": 2048,
    },
    "script_dropper.bin": {
        "text": (
            "WScript.Shell\npowershell -enc\nFromBase64String\n"
            "Invoke-WebRequest\nschtasks /create\nGetUserName\n"
        )
        * 3,
        "random_bytes": 128,
    },
    "vm_aware_stub.bin": {
        "text": "IsDebuggerPresent\nCheckRemoteDebuggerPresent\nvmware\nVBoxService\nsysteminfo\n" * 3,
        "random_bytes": 512,
    },
    "empty.bin": {"text": "", "random_bytes": 0},
}


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    rng = random.Random(SEED)
    for name, spec in SAMPLES.items():
        payload = spec["text"].encode("ascii")
        if spec["random_bytes"]:
            payload += bytes(rng.randrange(256) for _ in range(spec["random_bytes"]))
        (OUT / name).write_bytes(payload)
        print(f"wrote {name} ({len(payload)} bytes)")
    (OUT / "README.md").write_text(
        "# Synthetic samples\n\n"
        "Generated by `fixtures/generate_samples.py`. These files contain plain ASCII "
        "strings and pseudo-random padding only. Nothing here is executable and nothing "
        "here is real malware. Regenerate with:\n\n"
        "    uv run python fixtures/generate_samples.py\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
